export const vehicles = [
    {
        id: 1,
        name: "McLaren 720S",
        type: "Supercar",
        price: 150,
        company: "Mclaren",
        image: "https://www.topgear.com/sites/default/files/images/cars-road-test/2017/07/9329ff07c91832786835b0ce9c5c75fe/rh_720sweb-10.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 212,
        },
    },
    {
        id: 2,
        name: "Porsche 911 GT3",
        type: "Sports Car",
        price: 120,
        company: "Porsche",
        image: "https://www.authentic-roads.com/wp-content/uploads/2021/08/1-porsche-911-gt3-2021-rt-hero-front.jpg",
        specifications: {
            year: 2023,
            transmission: "Manual",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 198,
        },
    },
    {
        id: 3,
        name: "Mercedes-AMG GT",
        type: "Luxury Sports Car",
        price: 130,
        company: "Mercedes",
        image: "https://i.gaw.to/content/photos/25/38/253875_2017_Mercedes-Benz_AMG_GT.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 193,
        },
    },
    {
        id: 4,
        name: "Audi R8",
        type: "Supercar",
        price: 140,
        company: "Audi",
        image: "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?q=80&w=2069&auto=format&fit=crop",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 205,
        },
    },
    {
        id: 5,
        name: "BMW M4",
        type: "Sports Car",
        price: 100,
        company: "BMW",
        image: "https://www.hdcarwallpapers.com/download/bmw_m4_csl_2022_4k-3840x2160.jpg",
        specifications: {
            year: 2023,
            transmission: "Manual",
            fuel: "Petrol",
            seats: 4,
            topSpeed: 180,
        },
    },
    {
        id: 6,
        name: "Ferrari F8 Tributo",
        type: "Supercar",
        price: 200,
        company: "Ferrari",
        image: "https://www.bavariamotors.be/img/cars/1-f8-1.jpg?q=90&s=718d615c5c9af2214d2e25aff74e3444",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 211,
        },
    },
    {
        id: 7,
        name: "Lamborghini Huracán EVO",
        type: "Supercar",
        price: 220,
        company: "Lamborghini",
        image: "https://www.hdcarwallpapers.com/download/lamborghini_huracan_evo_fluo_capsule_5k_2-1920x1080.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 202,
        },
    },
    {
        id: 8,
        name: "Aston Martin DBS",
        type: "Grand Tourer",
        price: 180,
        company: "Aston Martin",
        image: "https://www.carscoops.com/wp-content/uploads/2022/02/2020-Aston-Martin-DBS.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 211,
        },
    },
    {
        id: 9,
        name: "Rolls-Royce Phantom",
        type: "Ultra Luxury",
        price: 300,
        company: "Rolls-Royce",
        image: "https://s1.cdn.autoevolution.com/images/gallery/ROLLS-ROYCE-Phantom-Coupe-5911_23.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 4,
            topSpeed: 155,
        },
    },
    {
        id: 10,
        name: "Bentley Continental GT",
        type: "Luxury Grand Tourer",
        price: 190,
        company: "Bentley",
        image: "https://www.pegasusautohouse.com/wp-content/uploads/2021/04/IMG_7610.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 4,
            topSpeed: 207,
        },
    },
    {
        id: 11,
        name: "Maserati MC20",
        type: "Supercar",
        price: 170,
        company: "Maserati",
        image: "https://www.carscoops.com/wp-content/uploads/2022/12/Maserati-MC20-WIth-ARIA-Bodykit-By-7-Design-House-26s.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 202,
        },
    },
    {
        id: 12,
        name: "Lexus LC 500",
        type: "Luxury Sports Car",
        price: 110,
        company: "Lexus",
        image: "https://images4.alphacoders.com/880/thumb-1920-880187.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 4,
            topSpeed: 168,
        },
    },
    {
        id: 13,
        name: "Bugatti Chiron",
        type: "Hypercar",
        price: 500,
        company: "Bugatti",
        image: "https://media.evo.co.uk/image/private/s--julLt06a--/v1556217571/evo/2017/08/bugatti_chiron_front_three_quarter.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 261,
        },
    },
    {
        id: 14,
        name: "Pagani Huayra",
        type: "Hypercar",
        price: 450,
        company: "Pagani",
        image: "https://images.unsplash.com/photo-1635974065147-4a72851190ef?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 238,
        },
    },
    {
        id: 15,
        name: "Koenigsegg Jesko",
        type: "Hypercar",
        price: 480,
        company: "Koenigsegg",
        image: "https://www.carscoops.com/wp-content/uploads/2019/04/ea5becbb-koenigsegg-jesko-.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 300,
        },
    },
    {
        id: 16,
        name: "Mercedes-Maybach S-Class",
        type: "Ultra Luxury",
        price: 250,
        company: "Mercedes",
        image: "https://s3.caradvice.com.au/wp-content/uploads/2015/01/15C2_331.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 4,
            topSpeed: 155,
        },
    },
    {
        id: 17,
        name: "Porsche Taycan Turbo S",
        type: "Electric Sports Car",
        price: 160,
        company: "Porsche",
        image: "https://s1.cdn.autoevolution.com/images/news/gallery/porsche-taycan-turbo-s-looks-epic-in-mamba-green_8.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Electric",
            seats: 4,
            topSpeed: 162,
        },
    },
    {
        id: 18,
        name: "Ferrari SF90 Stradale",
        type: "Hybrid Supercar",
        price: 280,
        company: "Ferrari",
        image: "https://www.hdcarwallpapers.com/download/ferrari_sf90_stradale_2020_5k_2-3840x2160.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Hybrid",
            seats: 2,
            topSpeed: 211,
        },
    },
    {
        id: 19,
        name: "Aston Martin Valkyrie",
        type: "Hypercar",
        price: 420,
        company: "Aston Martin",
        image: "https://hagerty.co.uk/wp-content/uploads/2023/03/Aston-Martin-Valkyrie-Night-2-scaled.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 250,
        },
    },
    {
        id: 20,
        name: "Lamborghini Aventador SVJ",
        type: "Supercar",
        price: 350,
        company: "Lamborghini",
        image: "https://images.unsplash.com/photo-1621135802920-133df287f89c?q=80&w=2070&auto=format&fit=crop",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 217,
        },
    },
    {
        id: 21,
        name: "McLaren P1",
        type: "Hybrid Hypercar",
        price: 400,
        company: "Mclaren",
        image: "https://www.supercars.net/blog/wp-content/uploads/2018/09/26-McLaren-P1.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Hybrid",
            seats: 2,
            topSpeed: 217,
        },
    },
    {
        id: 22,
        name: "Lotus Evija",
        type: "Electric Hypercar",
        price: 430,
        company: "Lotus",
        image: "https://smartcdn.gprod.postmedia.digital/driving/wp-content/uploads/2022/10/LOT_0806_Fittipaldi_Evija-scaled.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Electric",
            seats: 2,
            topSpeed: 200,
        },
    },
    {
        id: 23,
        name: "Aston Martin Valhalla",
        type: "Hybrid Hypercar",
        price: 380,
        company: "Aston Martin",
        image: "https://images.carexpert.com.au/resize/3000/-/app/uploads/2022/04/Valhalla-019.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Hybrid",
            seats: 2,
            topSpeed: 217,
        },
    },
    {
        id: 24,
        name: "Bentley Flying Spur",
        type: "Ultra Luxury",
        price: 230,
        company: "Bentley",
        image: "https://media.autoexpress.co.uk/image/private/s--Iy114UP0--/v1602666123/autoexpress/2020/10/Bentley%20Flying%20Spur%20V8%202020.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 4,
            topSpeed: 198,
        },
    },
    {
        id: 25,
        name: "Rimac Nevera",
        type: "Electric Hypercar",
        price: 460,
        company: "Rimac",
        image: "https://i.gaw.to/vehicles/photos/40/30/403015-2023-rimac-nevera.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Electric",
            seats: 2,
            topSpeed: 258,
        },
    },
    {
        id: 26,
        name: "Rolls-Royce Cullinan",
        type: "Ultra Luxury SUV",
        price: 280,
        company: "Rolls-Royce",
        image: "https://i.gaw.to/vehicles/photos/40/21/402185-2020-rolls-royce-cullinan.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 5,
            topSpeed: 155,
        },
    },
    {
        id: 27,
        name: "Ferrari 812 Competizione",
        type: "Grand Tourer",
        price: 260,
        company: "Ferrari",
        image: "https://www.hdcarwallpapers.com/download/ferrari_812_competizione_2021_5k_3-2560x1440.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 211,
        },
    },
    {
        id: 28,
        name: "Lamborghini Sián",
        type: "Hybrid Supercar",
        price: 390,
        company: "Lamborghini",
        image: "https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?q=80&w=2071&auto=format&fit=crop",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Hybrid",
            seats: 2,
            topSpeed: 220,
        },
    },
    {
        id: 29,
        name: "Mercedes-AMG ONE",
        type: "Formula 1 Hybrid",
        price: 470,
        company: "Mercedes",
        image: "https://cdn.motor1.com/images/mgl/pbbepW/s3/mercedes-amg-one-production.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Hybrid",
            seats: 2,
            topSpeed: 219,
        },
    },
    {
        id: 30,
        name: "Pininfarina Battista",
        type: "Electric Hypercar",
        price: 440,
        company: "Pininfarina",
        image: "https://www.carscoops.com/wp-content/uploads/2020/02/Pininfarina-Battista-Test-Mule-00.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Electric",
            seats: 2,
            topSpeed: 217,
        },
    },
];
