export const vehicles = [
    {
        id: 1,
        name: "McLaren 720S",
        type: "Supercar",
        price: 150,
        company: "Mclaren",
        image: "https://i.redd.it/ue7ixmwwu1p41.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 212,
        },
    },
    {
        id: 2,
        name: "Porsche 911 GT3",
        type: "Sports Car",
        price: 120,
        company: "Porsche",
        image: "https://blogmedia.dealerfire.com/wp-content/uploads/sites/1149/2021/04/2022-porsche-911-gt3-white_o-1536x864.jpg",
        specifications: {
            year: 2023,
            transmission: "Manual",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 198,
        },
    },
    {
        id: 3,
        name: "Mercedes-AMG GT",
        type: "Luxury Sports Car",
        price: 130,
        company: "Mercedes",
        image: "https://www.carscoops.com/wp-content/uploads/2020/07/2021-Mercedes-AMG-GT-Black-Series-4-1.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 193,
        },
    },
    {
        id: 4,
        name: "Audi R8",
        type: "Supercar",
        price: 140,
        company: "Audi",
        image: "https://cdn.motor1.com/images/mgl/VzM4p7/s1/audi-r8-japan-final-edition.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 205,
        },
    },
    {
        id: 5,
        name: "BMW M4",
        type: "Sports Car",
        price: 100,
        company: "BMW",
        image: "https://th.bing.com/th/id/R.0b0fc633eaebd5e8c8568fd6f210153a?rik=R%2f8Cf%2bsdrO4tDQ&riu=http%3a%2f%2fwww.automotiveaddicts.com%2fwp-content%2fuploads%2f2013%2f08%2fbmw-m4-coupe-concept.jpg&ehk=SkOq4etkC9ibTFcgAu4VHPwnYt5mb2kQBfp84ZVoXBY%3d&risl=&pid=ImgRaw&r=0",
        specifications: {
            year: 2023,
            transmission: "Manual",
            fuel: "Petrol",
            seats: 4,
            topSpeed: 180,
        },
    },
    {
        id: 6,
        name: "Ferrari F8 Tributo",
        type: "Supercar",
        price: 200,
        company: "Ferrari",
        image: "https://www.bavariamotors.be/img/cars/1-f8-1.jpg?q=90&s=718d615c5c9af2214d2e25aff74e3444",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 211,
        },
    },
    {
        id: 7,
        name: "Lamborghini Huracán EVO",
        type: "Supercar",
        price: 220,
        company: "Lamborghini",
        image: "https://www.hdcarwallpapers.com/download/lamborghini_huracan_evo_fluo_capsule_5k_2-1920x1080.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 202,
        },
    },
    {
        id: 8,
        name: "Aston Martin DBS",
        type: "Grand Tourer",
        price: 180,
        company: "Aston Martin",
        image: "https://www.carscoops.com/wp-content/uploads/2022/02/2020-Aston-Martin-DBS.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 211,
        },
    },
    {
        id: 9,
        name: "Rolls-Royce Phantom",
        type: "Ultra Luxury",
        price: 300,
        company: "Rolls-Royce",
        image: "https://blog-cdn.el.olx.com.pk/wp-content/uploads/2022/08/25165341/Rolls-Royce-Phantom-Exterior-O.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 4,
            topSpeed: 155,
        },
    },
    {
        id: 10,
        name: "Bentley Continental GT",
        type: "Luxury Grand Tourer",
        price: 190,
        company: "Bentley",
        image: "https://www.pegasusautohouse.com/wp-content/uploads/2021/04/IMG_7610.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 4,
            topSpeed: 207,
        },
    },
    {
        id: 11,
        name: "Maserati MC20",
        type: "Supercar",
        price: 170,
        company: "Maserati",
        image: "https://www.carscoops.com/wp-content/uploads/2022/12/Maserati-MC20-WIth-ARIA-Bodykit-By-7-Design-House-26s.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 202,
        },
    },
    {
        id: 12,
        name: "Lexus LC 500",
        type: "Luxury Sports Car",
        price: 110,
        company: "Lexus",
        image: "https://www.carscoops.com/wp-content/uploads/2019/08/65de6963-2020-lexus-lc-500-inspiration-series-0.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 4,
            topSpeed: 168,
        },
    },
    {
        id: 13,
        name: "Bugatti Chiron",
        type: "Hypercar",
        price: 500,
        company: "Bugatti",
        image: "https://luxurylaunches.com/wp-content/uploads/2019/09/Bugatti-Chiron-Super-Sport-300-1.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 261,
        },
    },
    {
        id: 14,
        name: "Pagani Huayra",
        type: "Hypercar",
        price: 450,
        company: "Pagani",
        image: "https://www.carscoops.com/wp-content/uploads/2021/01/Pagani-Huayra-BC-1a.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 238,
        },
    },
    {
        id: 15,
        name: "Koenigsegg Jesko",
        type: "Hypercar",
        price: 480,
        company: "Koenigsegg",
        image: "https://www.carscoops.com/wp-content/uploads/2019/04/ea5becbb-koenigsegg-jesko-.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 300,
        },
    },
    {
        id: 16,
        name: "Mercedes-Maybach S-Class",
        type: "Ultra Luxury",
        price: 250,
        company: "Mercedes",
        image: "https://media.ed.edmunds-media.com/mercedes-benz/maybach/2016/oem/2016_mercedes-benz_maybach_sedan_s600_fq_oem_15_1280.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 4,
            topSpeed: 155,
        },
    },
    {
        id: 17,
        name: "Porsche Taycan Turbo S",
        type: "Electric Sports Car",
        price: 160,
        company: "Porsche",
        image: "https://s1.cdn.autoevolution.com/images/news/gallery/porsche-taycan-turbo-s-looks-epic-in-mamba-green_8.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Electric",
            seats: 4,
            topSpeed: 162,
        },
    },
    {
        id: 18,
        name: "Ferrari SF90 Stradale",
        type: "Hybrid Supercar",
        price: 280,
        company: "Ferrari",
        image: "https://www.hdcarwallpapers.com/download/ferrari_sf90_stradale_2020_5k_2-3840x2160.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Hybrid",
            seats: 2,
            topSpeed: 211,
        },
    },
    {
        id: 19,
        name: "Aston Martin Valkyrie",
        type: "Hypercar",
        price: 420,
        company: "Aston Martin",
        image: "https://hagerty.co.uk/wp-content/uploads/2023/03/Aston-Martin-Valkyrie-Night-2-scaled.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 250,
        },
    },
    {
        id: 20,
        name: "Lamborghini Aventador SVJ",
        type: "Supercar",
        price: 350,
        company: "Lamborghini",
        image: "https://images.unsplash.com/photo-1621135802920-133df287f89c?q=80&w=2070&auto=format&fit=crop",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 217,
        },
    },
    {
        id: 21,
        name: "McLaren P1",
        type: "Hybrid Hypercar",
        price: 400,
        company: "Mclaren",
        image: "https://i.pinimg.com/originals/2a/f5/7b/2af57be2efaf1fb67949e8ec14341b4a.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Hybrid",
            seats: 2,
            topSpeed: 217,
        },
    },
    {
        id: 22,
        name: "Lotus Evija",
        type: "Electric Hypercar",
        price: 430,
        company: "Lotus",
        image: "https://images.carexpert.com.au/resize/3000/-/app/uploads/2020/05/Lotus-Evija-CarExpert-Specification-13-1.jpeg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Electric",
            seats: 2,
            topSpeed: 200,
        },
    },
    {
        id: 23,
        name: "Aston Martin Valhalla",
        type: "Hybrid Hypercar",
        price: 380,
        company: "Aston Martin",
        image: "https://conteudo.imguol.com.br/c/entretenimento/4c/2019/08/01/aston-martin-valhalla-1564675346782_v2_1920x1279.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Hybrid",
            seats: 2,
            topSpeed: 217,
        },
    },
    {
        id: 24,
        name: "Bentley Flying Spur",
        type: "Ultra Luxury",
        price: 230,
        company: "Bentley",
        image: "https://cdn.motor1.com/images/mgl/eo6AA8/s1/2023-flying-spur-s-v8-1.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 4,
            topSpeed: 198,
        },
    },
    {
        id: 25,
        name: "Rimac Nevera",
        type: "Electric Hypercar",
        price: 460,
        company: "Rimac",
        image: "https://cdn.motor1.com/images/mgl/y228Mo/s1/2023-rimac-nevera-first-drive-review.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Electric",
            seats: 2,
            topSpeed: 258,
        },
    },
    {
        id: 26,
        name: "Rolls-Royce Cullinan",
        type: "Ultra Luxury SUV",
        price: 280,
        company: "Rolls-Royce",
        image: "https://autonxt.net/wp-content/uploads/2020/08/2020-Rolls-Royce-Cullinan16.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 5,
            topSpeed: 155,
        },
    },
    {
        id: 27,
        name: "Ferrari 812 Competizione",
        type: "Grand Tourer",
        price: 260,
        company: "Ferrari",
        image: "https://autoinfo.co.th/uploads/2023/08/Ferrari-812-Novitec-tune-11.jpeg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Petrol",
            seats: 2,
            topSpeed: 211,
        },
    },
    {
        id: 28,
        name: "Lamborghini Sián",
        type: "Hybrid Supercar",
        price: 390,
        company: "Lamborghini",
        image: "https://www.team-bhp.com/forum/attachments/international-automotive-scene/2130327d1615260294-lamborghini-sian-debuts-brands-1st-electrified-production-car-lamborghinisianinpurplegreenandwhitethreequarterabovephotobyjuanpablosaenz.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Hybrid",
            seats: 2,
            topSpeed: 220,
        },
    },
    {
        id: 29,
        name: "Mercedes-AMG ONE",
        type: "Formula 1 Hybrid",
        price: 470,
        company: "Mercedes",
        image: "https://cdn.motor1.com/images/mgl/pbbepW/s3/mercedes-amg-one-production.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Hybrid",
            seats: 2,
            topSpeed: 219,
        },
    },
    {
        id: 30,
        name: "Pininfarina Battista",
        type: "Electric Hypercar",
        price: 440,
        company: "Pininfarina",
        image: "https://automotiveblog.co.uk/wp-content/uploads/2021/10/Automobili-Pininfarinas-Battista-hyper-GT.jpg",
        specifications: {
            year: 2023,
            transmission: "Automatic",
            fuel: "Electric",
            seats: 2,
            topSpeed: 217,
        },
    },
];

